- name: remove war file from ansible
  file:
    path: /home/ansible/provision/roles/cicd/files/my-webapp-1.0-SNAPSHOT.war
    state: absent
  when: inventory_hostname == 'localhost'

- name: remove war file from tomcat
  file:
    path: /opt/tomcat/webapps/my-webapp-1.0-SNAPSHOT.war
    state: absent
  when: inventory_hostname == '10.10.10.14'

- name: remove war file from tomcat
  file:
    path: /opt/tomcat/webapps/my-webapp-1.0-SNAPSHOT
    state: absent
  when: inventory_hostname == '10.10.10.14'

- name: fetch from git
  fetch:
    src: /home/my-java-app/target/my-webapp-1.0-SNAPSHOT.war
    dest: /home/ansible/provision/roles/cicd/files/
    flat: yes
  when: inventory_hostname == '10.10.10.20'

- name: copy to tomcat
  copy:
    src: /home/ansible/provision/roles/cicd/files/my-webapp-1.0-SNAPSHOT.war
    dest: /opt/tomcat/webapps/
  when: inventory_hostname == '10.10.10.14'
